### ISSUE TITLE
Implement styles in JS approach

### ISSUE THREAD

**Issue by davenotik** [woven/woven-react#2]
We've agreed styles in JS have benefits we'd like to further explore. I'd like to use one of the more common approaches to styles in JS.

**Comment by kaisellgren** [comment]
https://github.com/FormidableLabs/radium/blob/master/docs/comparison/README.md

**Comment by kaisellgren** [comment]
Radium looks decent, although no support for custom behaviors.

**Comment by kaisellgren** [comment]
Let's stay with Radium at least for now.
